### ISSUE TITLE
The very first screen to see after sign up

### ISSUE THREAD

**Issue by TaiMino** [blockchainProject/blockchain-project-client#125]
### Goal
Change the very first screen to see after sign up

### Observed behavior
Right now, it is profile page

### Expected behavior
Change it to home feed

### Steps

Change the first parameter of loadProfile (line 546) to 'home' as shown in the following codes.

  onboardingModal.on('onboarding-complete', function(guid) {
    app.serverConnectModal.succeedConnection(app.serverConfigs.getActive());
    onboardingModal && onboardingModal.remove();
    onboardingModal = null;
    loadProfile('home', true);
    //loadProfile('#userPage/' + guid + '/store', true);
    startUpLoadingModal.open();
  });

**Comment by florabrothers** [comment]
Users are now directed to home page after signing up :)
