### ISSUE TITLE
Unable to load home feed "slice" Typeerror

### ISSUE THREAD

**Issue by florabrothers** [blockchainProject/blockchain-project-client#141]
### Observed behavior
"slice" Typeerror when loading the home feed, the error occurred from the 291 line in blockchain-project-client\view\onboardingModal.js .

### Expected behavior
Electron should load the home feed after successfully connecting to the server.

### Steps
Change the themeId to the following:

    var themeId = this.$('input[name=theme-selection]:checked');
    if (themeId.length > 0){
      var primaryColor = parseInt(themeId.data('primary-color').slice(1), 16),
          secondaryColor = parseInt(themeId.data('secondary-color').slice(1), 16),
          backgroundColor = parseInt(themeId.data('background-color').slice(1), 16),
          textColor = parseInt(themeId.data('text-color').slice(1), 16);

### Questions
The bug is fixed from my side, so commit?

**Comment by TaiMino** [comment]
Thanks!  Isn't it better to run the process in the background as it can make the app faster?

**Comment by florabrothers** [comment]
Electron could not load the colour (I changed it to primary and secondary color) and that was it. The process still runs in the background :)
