### ISSUE TITLE
Global Shortcut Backspace Interferes with text editing

### ISSUE THREAD

**Issue by LiveMynd** [blockchainProject/blockchain-project-client#203]
[Template for Bug label]
### Observed behavior
Pressing the backspace button causes the app to return to the previous page, even if one is editing text.

### Expected behavior
Backspace should not go to previous page when editing text.

### Steps
(To reproduce)
1) Get to the User Settings page (through the profile icon -> Settings / Ctrl +G, because the main GUI is whack).
2) Click on any editable textbox. 
3) Make a mistake and press backspace to delete text.
4) Get taken to the previous page.
5) Wonder if your changes are lost and imagine trying to write something while using Delete instead of Backspace for corrections.

### Questions
1) I know that Backspace is used as a "previous page" shortcut on Web browsers (personally, I prefer Alt + Left Arrow). However, this behavior is overridden when editing text with the expected behavior of deleting the character prior to the text cursor. I imagine this UI interaction was overlooked when Global Shortcuts were implemented? In any case, I'll go ahead and look into fixing it by adding an override when editing a textbox.

**Comment by TaiMino** [comment]
Right, we didn't notice this would happen.  I guess Windows user use Alt + Left arrow?  I believe Macintosh user uses Command + Left Arrow.

**Comment by LiveMynd** [comment]
I've edited the global shortcut behavior to check if document.activeElement is a fieldItem or fieldItem-textArea, and to return if so. Otherwise, it continues on to the previous page behavior. Committed, merged to master, and pushed.

Incidentally, what's are our policy/practices for merging? For example, should I push my separate branch to the remote repo and ask for a review -> merge request?
